# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       tar

# >> macros
# << macros

# >> bcond_with
# << bcond_with

# >> bcond_without
# << bcond_without

Summary:    A GNU file archiving program
Version:    1.28
Release:    2
Group:      Applications/Archiving
License:    GPLv3+
URL:        http://www.gnu.org/software/tar/
Source0:    %{name}-%{version}.tar.xz
Source1:    tar.1
Source100:  tar.yaml
BuildRequires:  gettext
BuildRequires:  libacl-devel
BuildRequires:  gzip
BuildRequires:  bzip2
BuildRequires:  lzma
BuildRequires:  lzo
BuildRequires:  xz

%description
The GNU tar program saves many files together in one archive and can
restore individual files (or all of the files) from that archive. Tar
can also be used to add supplemental files to an archive and to update
or list files in the archive. Tar includes multivolume support,
automatic archive compression/decompression, the ability to perform
remote archives, and the ability to perform incremental and full
backups.

If you want to use tar for remote backups, you also need to install
the rmt package.


%prep
%setup -q -n src

# >> setup
%docs_package

%lang_package
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --bindir=/bin

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
mkdir -p %{buildroot}%{_mandir}/man1
cp -a %{SOURCE1} %{buildroot}%{_mandir}/man1


# >> install post
rm -rf %{buildroot}%{_prefix}/libexec/rmt
# << install post

%find_lang tar

%files -f tar.lang
%defattr(-,root,root,-)
%doc AUTHORS
/bin/tar
# >> files
# << files
